# Generated by Django 5.0.4 on 2026-01-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
