# Generated by Django 5.0.4 on 2026-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_ensure_cascade_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='repeat',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], max_length=20, null=True),
        ),
    ]
