"""
PDF export utility for summaries and study materials.
Uses reportlab for lightweight, dependency-free PDF generation.
"""

from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_LEFT, TA_CENTER


def generate_summary_pdf(summary_text: str, title: str = "Study Summary", course_code: str = "") -> BytesIO:
    """
    Generate a formatted PDF from summary text.
    
    Args:
        summary_text: The summary content to include in PDF
        title: PDF title/heading
        course_code: Optional course code for header
    
    Returns:
        BytesIO object containing PDF data (ready to serve as download)
    """
    # Create in-memory PDF buffer
    pdf_buffer = BytesIO()
    
    # Create PDF document
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=1 * inch,
        bottomMargin=0.75 * inch,
    )
    
    # Get stylesheet and customize
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor='#1e3a8a',
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold',
    )
    
    meta_style = ParagraphStyle(
        'Meta',
        parent=styles['Normal'],
        fontSize=10,
        textColor='#666666',
        alignment=TA_CENTER,
        spaceAfter=12,
        fontName='Helvetica-Oblique',
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        leading=14,
        alignment=TA_LEFT,
        spaceAfter=8,
        fontName='Helvetica',
    )
    
    # Build PDF content
    story = []
    
    # Title
    story.append(Paragraph(title, title_style))
    
    # Metadata
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    course_text = f"{course_code} • " if course_code else ""
    story.append(Paragraph(f"{course_text}{timestamp}", meta_style))
    story.append(Spacer(1, 0.2 * inch))
    
    # Summary content
    # Handle section headers (lines starting with \n and ending with :)
    paragraphs = summary_text.split('\n')
    for para in paragraphs:
        para = para.strip()
        if not para:
            story.append(Spacer(1, 0.1 * inch))
            continue
        
        # Detect section headers (simple heuristic: short lines ending with :)
        if para.endswith(':') and len(para) < 50:
            section_style = ParagraphStyle(
                'Section',
                parent=styles['Heading2'],
                fontSize=13,
                textColor='#1e3a8a',
                spaceAfter=6,
                spaceBefore=8,
                fontName='Helvetica-Bold',
            )
            story.append(Paragraph(para, section_style))
        else:
            story.append(Paragraph(para, body_style))
    
    # Footer with generation note
    story.append(Spacer(1, 0.3 * inch))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor='#999999',
        alignment=TA_CENTER,
        fontName='Helvetica-Oblique',
    )
    story.append(Paragraph(
        "Generated by Coursebook Preparation System",
        footer_style
    ))
    
    # Build PDF
    doc.build(story)
    pdf_buffer.seek(0)
    
    return pdf_buffer
