# Generated by Django 5.0.4 on 2026-01-01 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageUsage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='storage_usage', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('used_bytes', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage usage',
                'verbose_name_plural': 'Storage usage',
            },
        ),
    ]
