# Generated by Django 5.0.4 on 2026-01-08 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_alter_course_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_type', models.CharField(choices=[('semester', 'Semester'), ('course', 'Course')], max_length=20)),
                ('semester_name', models.CharField(blank=True, max_length=100, null=True)),
                ('share_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('privacy', models.CharField(choices=[('public', 'Public - Anyone with the link'), ('coursebook_users', 'Coursebook Users Only')], default='public', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'share_type'], name='sharing_sha_user_id_f99e42_idx'), models.Index(fields=['share_token'], name='sharing_sha_share_t_8cf4fd_idx')],
            },
        ),
    ]
