# Generated by Django 5.0.4 on 2026-01-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private - Only me'), ('public', 'Public - Anyone with the link'), ('coursebook_users', 'Coursebook Users Only')], default='public', max_length=20),
        ),
    ]
