# Generated by Django 5.0.4 on 2026-01-03 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'code']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('user', 'folder_slug')},
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('user', 'code', 'semester'), ('user', 'folder_slug')},
        ),
    ]
