# Generated by Django 5.0.4 on 2026-01-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='semester',
            name='order',
            field=models.IntegerField(default=0, help_text='Custom order for sorting semesters'),
        ),
    ]
