# Generated by Django 5.0.4 on 2026-01-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_trash_bin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='material',
            new_name='materials_m_user_id_c5ab04_idx',
            old_name='materials_m_user_id_is_del_idx',
        ),
        migrations.RenameIndex(
            model_name='material',
            new_name='materials_m_deleted_39242b_idx',
            old_name='materials_m_deleted_idx',
        ),
    ]
