# Generated by Django 5.0.4 on 2026-01-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_rename_materials_m_user_id_is_del_idx_materials_m_user_id_c5ab04_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private - Only me'), ('public', 'Public - Anyone with the link'), ('coursebook_users', 'Coursebook Users Only')], db_index=True, default='private', max_length=20),
        ),
    ]
